/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package irrigationmanagementsystem;

import java.awt.Component;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Sandeepa Madhusanka
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate1 = new datechooser.beans.DateChooserCombo();
        closeButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        txtDate2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Annual Reports");

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Start Date");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("End Date");

        txtDate1.setCalendarPreferredSize(new java.awt.Dimension(400, 260));
        txtDate1.setFormat(1);
        try {
            txtDate1.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2014, 0, 1),
                new java.util.GregorianCalendar(2014, 0, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    txtDate1.setFieldFont(new java.awt.Font("Tw Cen MT", java.awt.Font.PLAIN, 16));

    closeButton.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    closeButton.setText("Close");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    printButton.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    printButton.setText("Print");
    printButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            printButtonActionPerformed(evt);
        }
    });

    txtDate2.setCalendarPreferredSize(new java.awt.Dimension(400, 260));
    try {
        txtDate2.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2015, 0, 22),
            new java.util.GregorianCalendar(2015, 0, 22))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    txtDate2.setFieldFont(new java.awt.Font("Tw Cen MT", java.awt.Font.PLAIN, 16));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDate1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGap(111, 111, 111)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDate2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGap(21, 21, 21)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printButton)
                    .addGap(18, 18, 18)
                    .addComponent(closeButton)))
            .addGap(39, 39, 39))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jScrollPane1)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2)
                .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeButton)
                .addComponent(printButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<ItemDetails> itemList;
    DBOperations dbOps = new DBOperations();
    
    public void loadItem(String first, String second) {
        itemList = dbOps.getReportDetails(first, second);
        ReportTable id = new ReportTable(itemList);

        tblReports.setModel(id);
        
        TableColumnModel tcm = tblReports.getColumnModel();
        tcm.getColumn(0).setMinWidth(80);
        tcm.getColumn(1).setMinWidth(100);
        tcm.getColumn(2).setMinWidth(80);
        tcm.getColumn(3).setMinWidth(120);
        tcm.getColumn(4).setMinWidth(120);
        tcm.getColumn(5).setMinWidth(120);
        tcm.getColumn(6).setMinWidth(40);
        tcm.getColumn(7).setMinWidth(40);
        tcm.getColumn(8).setMinWidth(40);
        tcm.getColumn(9).setMinWidth(50);
        tcm.getColumn(10).setMinWidth(80);
        tcm.getColumn(11).setMinWidth(80);
        tcm.getColumn(12).setMinWidth(50);
        tcm.getColumn(13).setMinWidth(50);
        tcm.getColumn(14).setMinWidth(30);
        
        //tblReports.setRowHeight(30);
//        tblReports.getColumnModel().getColumn(0).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(1).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(2).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(3).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(4).setCellRenderer(new MyCellRenderer());
//       tblReports.getColumnModel().getColumn(5).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(6).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(7).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(8).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(9).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(10).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(11).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(12).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(13).setCellRenderer(new MyCellRenderer());
//        tblReports.getColumnModel().getColumn(14).setCellRenderer(new MyCellRenderer());        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("MMM dd, yyyy");
            String dateInString1 = txtDate1.getText();
            Date date1 = formatter.parse(dateInString1);
            String first = new SimpleDateFormat("yyyy-MM-dd").format(date1);
            String dateInString2 = txtDate2.getText();
            Date date2 = formatter.parse(dateInString2);
            String second = new SimpleDateFormat("yyyy-MM-dd").format(date2);
            loadItem(first, second);
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Some required fields are empty!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
                boolean complete = tblReports.print();
                if (complete) {

                } else {

                }
            } catch (PrinterException pe) {

            }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JTable tblReports;
    private datechooser.beans.DateChooserCombo txtDate1;
    private datechooser.beans.DateChooserCombo txtDate2;
    // End of variables declaration//GEN-END:variables
}

class MyCellRenderer extends JTextArea implements TableCellRenderer {
     public MyCellRenderer() {
       setLineWrap(true);
       setWrapStyleWord(true);
    }
     
    int max=0;

   public Component getTableCellRendererComponent(JTable table, Object
           value, boolean isSelected, boolean hasFocus, int row, int column) {
       setText(String.valueOf(value));//or something in value, like value.getNote()...
       if (table.getRowHeight(row) != getPreferredSize().height && table.getRowHeight(row)>max) {
               table.setRowHeight(row, getPreferredSize().height);
               max=table.getRowHeight(row);
       }
       return this;
   }
} 
